export const SET__LOGIN = "SET__LOGIN";
export const RESET__LOGIN = "RESET__LOGIN";

export const SET__AUTH_MODAL_TOGGLE = "SET__AUTH_MODAL_TOGGLE";
export const RESET__AUTH_MODAL_TOGGLE = "RESET__AUTH_MODAL_TOGGLE";

export const SET__AUTH_MODAL = "SET__AUTH_MODAL";
export const RESET__AUTH_MODAL = "RESET__AUTH_MODAL";
